### PR TITLE
fix: NullPointException when statistics query is null

### PR DESCRIPTION
**Pull request by bobdxiao**
When I used bigquery, I found a null pointer exception. I learned that the project uses JDK8, so I used Optional to rewrite this part of the code to avoid this exception.

### CODE REVIEW

**Comment by bobdxiao** [comment]
Contributor License Agreement (CLA) signed.

**Comment by bobdxiao** [comment]
Found the same issue in BQForwardOnlyResultSet and BQStatement, so I submitted a new commit

**Review by tjbanghart — APPROVED** [review]
Thanks for the PR! LGTM

**Comment by tjbanghart** [comment]
Merged in https://github.com/looker-open-source/bqjdbc/commit/f00d793ab2a344c430830deed85aede60cbf1993. Thank you!

**Pull request closed without merging**
